# Generated by Django 5.2.4 on 2025-07-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferred_categories',
            new_name='categories',
        ),
    ]
